In [1]:
!pip -q install transformers==4.52.4
!pip install huggingface-hub==0.36.2
!pip -q install datasets
!pip -q install sentencepiece
!pip -q install sacrebleu
!pip -q install bert-score
!pip -q install evaluate
!pip -q install accelerate

Requirement already satisfied: huggingface-hub==0.36.2 in /usr/local/lib/python3.12/dist-packages (0.36.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (4.67.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.36.2) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub==0.36.2) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub==0.36.2) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub==0.36.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub==0.36.2) (2026.6.17)

In [2]:
import os
import random
import time
import numpy as np
import pandas as pd
import torch

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

os.environ["PYTHONHASHSEED"] = str(SEED)

torch.backends.cudnn.deterministic=True
torch.backends.cudnn.benchmark=False

print(torch.cuda.get_device_name(0))

Tesla T4

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Datasets.zip to Datasets (2).zip

In [4]:
import zipfile

zipfile.ZipFile("Datasets.zip").extractall("dataset")

In [5]:
import os

for root, dirs, files in os.walk("dataset"):
    for f in files:
        print(f)

train_en_10000.csv
test_en_1000.csv
train_sa_10000.csv
dev_sa_1000.csv
dev_en_1000.csv
test_sa_1000.csv

In [6]:
train_sa = pd.read_csv("dataset/train_sa_10000.csv")
train_en = pd.read_csv("dataset/train_en_10000.csv")

dev_sa = pd.read_csv("dataset/dev_sa_1000.csv")
dev_en = pd.read_csv("dataset/dev_en_1000.csv")

test_sa = pd.read_csv("dataset/test_sa_1000.csv")
test_en = pd.read_csv("dataset/test_en_1000.csv")

In [7]:
print("train_sa columns:", train_sa.columns.tolist())
print("train_en columns:", train_en.columns.tolist())

print("\nFirst Sanskrit rows")
print(train_sa.head())

print("\nFirst English rows")
print(train_en.head())

train_sa columns: ['Source_id', 'Sentence_sa']
train_en columns: ['Source_id', 'Sentence_en']

First Sanskrit rows
   Source_id                                        Sentence_sa
0          1                         "Ctrl, S नुत्वा रक्षन्तु।"
1          2                     गुरुः छात्रान् एकवारं पाठयति ।
2          3  चित्रचालनमिदं पुनः कर्तुं मया अस्याः राशेः चित...
3          4       वयं  Colors विकल्पं तस्योपरि नोदनेन चिनुमः ।
4          5  "अत्र कानिचन उदाहरणानि पश्याम:- एक: पर्वत:, चत...

First English rows
   Source_id                                        Sentence_en
0          1                              Save it with Ctrl, S.
1          2         Teacher will teach the students only once.
2          3  To recreate this animation, I have to take two...
3          4    I will choose Colors options by clicking on it.
4          5  "See the example here - one mountain, four vil...

In [8]:
train = train_sa.merge(train_en,on="Source_id")
dev = dev_sa.merge(dev_en,on="Source_id")
test = test_sa.merge(test_en,on="Source_id")

train.head()

,Source_id,Sentence_sa,Sentence_en
0,1,"""Ctrl, S नुत्वा रक्षन्तु।""","Save it with Ctrl, S."
1,2,गुरुः छात्रान् एकवारं पाठयति ।,Teacher will teach the students only once.
2,3,चित्रचालनमिदं पुनः कर्तुं मया अस्याः राशेः चित...,"To recreate this animation, I have to take two..."
3,4,वयं Colors विकल्पं तस्योपरि नोदनेन चिनुमः ।,I will choose Colors options by clicking on it.
4,5,"""अत्र कानिचन उदाहरणानि पश्याम:- एक: पर्वत:, चत...","""See the example here - one mountain, four vil..."

In [9]:
from datasets import Dataset

train_ds = Dataset.from_pandas(train)
dev_ds = Dataset.from_pandas(dev)
test_ds = Dataset.from_pandas(test)

In [10]:
from transformers import AutoTokenizer

MODEL="facebook/nllb-200-distilled-600M"

tokenizer=AutoTokenizer.from_pretrained(MODEL)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

In [11]:
SRC_LANG="san_Deva"
TGT_LANG="eng_Latn"

tokenizer.src_lang=SRC_LANG
tokenizer.tgt_lang=TGT_LANG

In [12]:
MAX_LEN = 128

def preprocess(batch):

    model_inputs = tokenizer(
        batch["Sentence_sa"],
        max_length=MAX_LEN,
        truncation=True
    )

    labels = tokenizer(
        text_target=batch["Sentence_en"],
        max_length=MAX_LEN,
        truncation=True
    )

    model_inputs["labels"] = labels["input_ids"]

    return model_inputs

In [13]:
train_ds = train_ds.map(preprocess, batched=True)
dev_ds = dev_ds.map(preprocess, batched=True)
test_ds = test_ds.map(preprocess, batched=True)

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [14]:
from transformers import AutoModelForSeq2SeqLM

model=AutoModelForSeq2SeqLM.from_pretrained(MODEL)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

M2M100ForConditionalGeneration(
  (model): M2M100Model(
    (shared): M2M100ScaledWordEmbedding(256206, 1024, padding_idx=1)
    (encoder): M2M100Encoder(
      (embed_tokens): M2M100ScaledWordEmbedding(256206, 1024, padding_idx=1)
      (embed_positions): M2M100SinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x M2M100EncoderLayer(
          (self_attn): M2M100SdpaAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (activation_fn): ReLU()
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (decoder): M2M100Decoder(
      (embed_tokens): M2M100ScaledWordEmbedding(256206, 1024, padding_idx=1)
      (embed_positions): M2M100SinusoidalPositionalEmbedding()
      (layers): ModuleList(
        (0-11): 12 x M2M100DecoderLayer(
          (self_attn): M2M100SdpaAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (activation_fn): ReLU()
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (encoder_attn): M2M100SdpaAttention(
            (k_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (v_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (q_proj): Linear(in_features=1024, out_features=1024, bias=True)
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (encoder_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
  )
  (lm_head): Linear(in_features=1024, out_features=256206, bias=False)
)

In [15]:
num_params=sum(p.numel() for p in model.parameters())

print("Parameters:",num_params)

Parameters: 615073792

In [16]:
from transformers import DataCollatorForSeq2Seq

collator=DataCollatorForSeq2Seq(tokenizer,model=model)

In [17]:
import transformers
print(transformers.__version__)

4.52.4

In [18]:
from transformers import Seq2SeqTrainingArguments
import inspect

print(inspect.signature(Seq2SeqTrainingArguments.__init__))

(self, output_dir: Optional[str] = None, overwrite_output_dir: bool = False, do_train: bool = False, do_eval: bool = False, do_predict: bool = False, eval_strategy: Union[transformers.trainer_utils.IntervalStrategy, str] = 'no', prediction_loss_only: bool = False, per_device_train_batch_size: int = 8, per_device_eval_batch_size: int = 8, per_gpu_train_batch_size: Optional[int] = None, per_gpu_eval_batch_size: Optional[int] = None, gradient_accumulation_steps: int = 1, eval_accumulation_steps: Optional[int] = None, eval_delay: Optional[float] = 0, torch_empty_cache_steps: Optional[int] = None, learning_rate: float = 5e-05, weight_decay: float = 0.0, adam_beta1: float = 0.9, adam_beta2: float = 0.999, adam_epsilon: float = 1e-08, max_grad_norm: float = 1.0, num_train_epochs: float = 3.0, max_steps: int = -1, lr_scheduler_type: Union[transformers.trainer_utils.SchedulerType, str] = 'linear', lr_scheduler_kwargs: Union[dict, str, NoneType] = <factory>, warmup_ratio: float = 0.0, warmup_steps: int = 0, log_level: Optional[str] = 'passive', log_level_replica: Optional[str] = 'warning', log_on_each_node: bool = True, logging_dir: Optional[str] = None, logging_strategy: Union[transformers.trainer_utils.IntervalStrategy, str] = 'steps', logging_first_step: bool = False, logging_steps: float = 500, logging_nan_inf_filter: bool = True, save_strategy: Union[transformers.trainer_utils.SaveStrategy, str] = 'steps', save_steps: float = 500, save_total_limit: Optional[int] = None, save_safetensors: Optional[bool] = True, save_on_each_node: bool = False, save_only_model: bool = False, restore_callback_states_from_checkpoint: bool = False, no_cuda: bool = False, use_cpu: bool = False, use_mps_device: bool = False, seed: int = 42, data_seed: Optional[int] = None, jit_mode_eval: bool = False, use_ipex: bool = False, bf16: bool = False, fp16: bool = False, fp16_opt_level: str = 'O1', half_precision_backend: str = 'auto', bf16_full_eval: bool = False, fp16_full_eval: bool = False, tf32: Optional[bool] = None, local_rank: int = -1, ddp_backend: Optional[str] = None, tpu_num_cores: Optional[int] = None, tpu_metrics_debug: bool = False, debug: Union[str, list[transformers.debug_utils.DebugOption]] = '', dataloader_drop_last: bool = False, eval_steps: Optional[float] = None, dataloader_num_workers: int = 0, dataloader_prefetch_factor: Optional[int] = None, past_index: int = -1, run_name: Optional[str] = None, disable_tqdm: Optional[bool] = None, remove_unused_columns: Optional[bool] = True, label_names: Optional[list[str]] = None, load_best_model_at_end: Optional[bool] = False, metric_for_best_model: Optional[str] = None, greater_is_better: Optional[bool] = None, ignore_data_skip: bool = False, fsdp: Union[list[transformers.trainer_utils.FSDPOption], str, NoneType] = '', fsdp_min_num_params: int = 0, fsdp_config: Union[dict, str, NoneType] = None, fsdp_transformer_layer_cls_to_wrap: Optional[str] = None, accelerator_config: Union[dict, str, NoneType] = None, deepspeed: Union[dict, str, NoneType] = None, label_smoothing_factor: float = 0.0, optim: Union[transformers.training_args.OptimizerNames, str] = 'adamw_torch', optim_args: Optional[str] = None, adafactor: bool = False, group_by_length: bool = False, length_column_name: Optional[str] = 'length', report_to: Union[NoneType, str, list[str]] = None, ddp_find_unused_parameters: Optional[bool] = None, ddp_bucket_cap_mb: Optional[int] = None, ddp_broadcast_buffers: Optional[bool] = None, dataloader_pin_memory: bool = True, dataloader_persistent_workers: bool = False, skip_memory_metrics: bool = True, use_legacy_prediction_loop: bool = False, push_to_hub: bool = False, resume_from_checkpoint: Optional[str] = None, hub_model_id: Optional[str] = None, hub_strategy: Union[transformers.trainer_utils.HubStrategy, str] = 'every_save', hub_token: Optional[str] = None, hub_private_repo: Optional[bool] = None, hub_always_push: bool = False, gradient_checkpointing: bool = False, gradient_checkpointing_kwargs: Union[dict, str, NoneType] = None, include_inputs_for_metrics: bool = False, include_for_metrics: list[str] = <factory>, eval_do_concat_batches: bool = True, fp16_backend: str = 'auto', push_to_hub_model_id: Optional[str] = None, push_to_hub_organization: Optional[str] = None, push_to_hub_token: Optional[str] = None, mp_parameters: str = '', auto_find_batch_size: bool = False, full_determinism: bool = False, torchdynamo: Optional[str] = None, ray_scope: Optional[str] = 'last', ddp_timeout: Optional[int] = 1800, torch_compile: bool = False, torch_compile_backend: Optional[str] = None, torch_compile_mode: Optional[str] = None, include_tokens_per_second: Optional[bool] = False, include_num_input_tokens_seen: Optional[bool] = False, neftune_noise_alpha: Optional[float] = None, optim_target_modules: Union[NoneType, str, list[str]] = None, batch_eval_metrics: bool = False, eval_on_start: bool = False, use_liger_kernel: Optional[bool] = False, eval_use_gather_object: Optional[bool] = False, average_tokens_across_devices: Optional[bool] = False, sortish_sampler: bool = False, predict_with_generate: bool = False, generation_max_length: Optional[int] = None, generation_num_beams: Optional[int] = None, generation_config: Union[str, pathlib.Path, transformers.generation.configuration_utils.GenerationConfig, NoneType] = None) -> None

In [19]:
from transformers import Seq2SeqTrainingArguments
import torch

args = Seq2SeqTrainingArguments(

    output_dir="checkpoint",

    learning_rate=3e-5,

    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,


    gradient_accumulation_steps=4,

    weight_decay=0.01,

    num_train_epochs=5,

    predict_with_generate=True,

    eval_strategy="epoch",

    save_strategy="epoch",

    logging_strategy="steps",
    logging_steps=50,

    save_total_limit=1,

    load_best_model_at_end=True,

    metric_for_best_model="eval_loss",
    greater_is_better=False,

    fp16=torch.cuda.is_available(),

    report_to="none",

    seed=42
)

In [20]:
import evaluate

bleu=evaluate.load("sacrebleu")

In [21]:
import numpy as np

def compute_metrics(eval_pred):

    predictions,labels=eval_pred

    decoded_preds=tokenizer.batch_decode(
        predictions,
        skip_special_tokens=True
    )

    labels=np.where(labels!=-100,labels,tokenizer.pad_token_id)

    decoded_labels=tokenizer.batch_decode(
        labels,
        skip_special_tokens=True
    )

    result=bleu.compute(
        predictions=decoded_preds,
        references=[[l] for l in decoded_labels]
    )

    return {"BLEU":result["score"]}

In [22]:
from transformers import Seq2SeqTrainer
from transformers import EarlyStoppingCallback

trainer = Seq2SeqTrainer(

    model=model,

    args=args,

    train_dataset=train_ds,

    eval_dataset=dev_ds,

    tokenizer=tokenizer,

    data_collator=collator,

    compute_metrics=compute_metrics,

    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

/tmp/ipykernel_14368/2762269934.py:4: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Seq2SeqTrainer.__init__`. Use `processing_class` instead.
  trainer = Seq2SeqTrainer(

In [23]:
import torch
print(torch.cuda.is_available())
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

True
Tesla T4

In [24]:
trainer.train()

Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

/usr/local/lib/python3.12/dist-packages/transformers/modeling_utils.py:3465: UserWarning: Moving the following attributes in the config to the generation config: {'max_length': 200}. You are seeing this warning because you've set generation parameters in the model config, as opposed to in the generation config.
  warnings.warn(
There were missing keys in the checkpoint model loaded: ['model.encoder.embed_tokens.weight', 'model.decoder.embed_tokens.weight', 'lm_head.weight'].

TrainOutput(global_step=3125, training_loss=1.3460783782958985, metrics={'train_runtime': 4909.8028, 'train_samples_per_second': 10.184, 'train_steps_per_second': 0.636, 'total_flos': 4453560797134848.0, 'train_loss': 1.3460783782958985, 'epoch': 5.0})

In [32]:
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Total Parameters      : {total_params:,}")
print(f"Trainable Parameters  : {trainable_params:,}")

Total Parameters      : 615,073,792
Trainable Parameters  : 615,073,792

In [25]:
from bert_score import score

preds = []

start = time.time()

model.eval()

for sent in test["Sentence_sa"]:

    inputs = tokenizer(
        sent,
        return_tensors="pt",
        truncation=True,
        max_length=128
    )

    inputs = {k: v.to(device) for k, v in inputs.items()}

    output = model.generate(

        **inputs,

        forced_bos_token_id=tokenizer.convert_tokens_to_ids("eng_Latn"),

        num_beams=5,

        length_penalty=1.2,

        no_repeat_ngram_size=3,

        max_length=128
    )

    preds.append(
        tokenizer.decode(
            output[0],
            skip_special_tokens=True
        )
    )

end = time.time()

print("Inference Time:", end-start)

Inference Time: 584.2857384681702

In [26]:
P,R,F=score(
    preds,
    test["Sentence_en"].tolist(),
    lang="en",
    rescale_with_baseline=True
)

print(F.mean())

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tensor(0.5982)

In [27]:
import sacrebleu

bleu=sacrebleu.corpus_bleu(
    preds,
    [test["Sentence_en"].tolist()]
)

print(bleu.score)

29.85486628578593

In [28]:
submission=pd.DataFrame()

submission["Source_id"]=test["Source_id"]

submission["Sentence_en"]=preds

submission.to_csv(
    "submission.csv",
    index=False,
    encoding="utf-8"
)

submission.head()

   Source_id                                        Sentence_en
0          1  It also helps in troubleshooting Eclipse program.
1          2  "By faith I speak: even as it is written, We a...
2          3  Then it will automatically search for the driv...
3          4  For all iterations, the iterator is set to the...
4          5  "And when he had opened the second seal, I hea...

In [29]:
from google.colab import files

files.download("submission.csv")

In [30]:
print(len(preds))
print(len(test["Sentence_en"]))

for i in range(5):
    print("="*80)
    print("Sanskrit :", test["Sentence_sa"].iloc[i])
    print("Reference:", test["Sentence_en"].iloc[i])
    print("Prediction:", preds[i])

1000
1000
================================================================================
Sanskrit : एक्लिप्स् इति प्रोग्रामर् कृते दोषान्वेषणे अपि साहाय्यं करोति।
Reference: Eclipse also helps the programmer to find out errors.
Prediction: It also helps in troubleshooting Eclipse program.
================================================================================
Sanskrit : विश्वासकारणादेव समभाषि मया वचः। इति यथा शास्त्रे लिखितं तथैवास्माभिरपि विश्वासजनकम् आत्मानं प्राप्य विश्वासः क्रियते तस्माच्च वचांसि भाष्यन्ते।
Reference: "We having the same spirit of faith, according as it is written, I believed, and therefore have I spoken; we also believe, and therefore speak;"
Prediction: "By faith I speak: even as it is written, We also have the spirit of faith,"
================================================================================
Sanskrit : तदा, तत्स्वयं ड्रैवर निमित्तम् अन्वेष्यति। अहं 'Cancel' इत्यस्योपरि नुदामि।
Reference: Then it will automatically begin searching for drivers. I will click on Cancel.
Prediction: Then it will automatically search for the driver. I will click on Cancel.
================================================================================
Sanskrit : सर्वेभ्यः इटरेशन्-अर्थम्, iterator इतीदं प्रत्येकस्मै इण्डेक्स्-वेल्यू-इत्यस्मै सेट् क्रियते । 1,1 पश्चात् 1,2  एवम्…
Reference: The iterator will be set to each of the indices values for each iteration- say, 1 comma 1, then 1 comma 2 and so on.
Prediction: For all iterations, the iterator is set to the index value of each. 1.1 followed by 1,2 is...
================================================================================
Sanskrit : अपरं द्वितीयमुद्रायां तेन मोचितायां द्वितीयस्य प्राणिन आगत्य पश्येति वाक् मया श्रुता।
Reference: "And when he had opened the second seal, I heard the second beast say, Come and see."
Prediction: "And when he had opened the second seal, I heard the voice of the second living creature, saying, Lo, I am."

In [31]:
from bert_score import score

P, R, F = score(
    preds,
    test["Sentence_en"].tolist(),
    model_type="roberta-large",
    num_layers=17,
    lang="en",
    rescale_with_baseline=False
)

print("Precision :", P.mean().item())
print("Recall    :", R.mean().item())
print("F1        :", F.mean().item())

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Precision : 0.9354918599128723
Recall    : 0.9291130304336548
F1        : 0.9321918487548828